Add tests for basic, (disabled) kerberos, and sso auth
neo4j-drivers/testkit pull request #237
Opened 2021-09-03 11:38 UTC by robsdedude

2021-09-03 11:50 UTC, gjmwoods approved these changes

2021-09-20 08:08 UTC, robsdedude commented on tests/stub/iteration/test_iteration_session_run.py
> +                            types.AuthorizationToken("basic",  principal="",
```suggestion
                            types.AuthorizationToken("basic", principal="",
```

2021-09-22 13:04 UTC, gjmwoods requested changes

2021-09-22 13:04 UTC, gjmwoods commented on tests/stub/authorization/scripts/v4x3/scheme_custom.script
> +A: HELLO {"user_agent": "*", "scheme": "wild-scheme", "principal": "I See Something", "credentials": "You Don't See!", "realm": "And it's blue.", "parameters": {"sky?": "no", "my eyes": 0.1, "da be d
😂

2021-09-22 13:04 UTC, gjmwoods commented on tests/stub/authorization/scripts/v4x3/scheme_kerberos.script
> +A: HELLO {"user_agent": "*", "scheme": "kerberos", "principal": "", "ticket": "QmFuYW5hIQ==", "[routing]": null, "[credential]": "", "[realm]": ""}
this is where things get fuzzy. I _think_ the Kerberos plugin expects a value of `ticket` for `scheme` (see https://github.com/neo-technology/kerberos-plugin#authenticating-with-kerberos). Java has `kerberos` for scheme and this would mean it would have always been broken for `AuthTokens.kerberos()`

2021-09-22 14:39 UTC, robsdedude commented on tests/stub/authorization/scripts/v4x3/scheme_kerberos.script
> +A: HELLO {"user_agent": "*", "scheme": "kerberos", "principal": "", "ticket": "QmFuYW5hIQ==", "[routing]": null, "[credential]": "", "[realm]": ""}
After digging into the code of the plugin with Florent, we came to the conclusion that the docs might be outdated. We are pretty sure it expects the token to be in the `credentials` field. Regarding the scheme, we had no luck to follow the control flow. Maybe we should contact Olivia who was pretty active in the plugin project to see if she can clarify how it all hangs together.

2021-09-28 12:09 UTC, robsdedude commented on tests/stub/authorization/scripts/v4x3/scheme_kerberos.script
> +A: HELLO {"user_agent": "*", "scheme": "kerberos", "principal": "", "ticket": "QmFuYW5hIQ==", "[routing]": null, "[credential]": "", "[realm]": ""}
Olivia confirmed that it belongs into the `credentials` field. Furthermore, she suggested, that the `scheme` actually doesn't matter at all. I suggest we enforce it to be `kerberos` in TestKit regardless.

2021-09-28 16:19 UTC, gjmwoods approved these changes

2021-10-01 08:50 UTC, robsdedude commented on nutkit/protocol/requests.py
> +        - parameters (dict[str, Any])
```suggestion
        - principal (str, optional)
        - credentials (str, optional)
        - realm (str, optional)
        - parameters (dict[str, Any], optional)
```

2021-10-01 12:29 UTC, merged