Notifications test case
neo4j-drivers/testkit pull request #548
Opened 2023-04-06 09:55 UTC by thelonelyvulpes

2023-04-06 10:44 UTC, injectives approved these changes

2023-04-06 10:45 UTC, injectives commented
We might need to update backends to permit `None` access mode.

2023-04-06 11:59 UTC, robsdedude requested changes

2023-04-06 11:59 UTC, robsdedude commented on tests/stub/notifications_config/test_session_notifications_config.py
> +                                             notifications_min_severity="WARNING")  # noqa: E501
```suggestion
                    session = driver.session(
                        None, notifications_min_severity="WARNING"
                    )
```

2023-04-06 11:59 UTC, robsdedude commented on tests/stub/notifications_config/test_session_notifications_config.py
> +            with self.subTest(name=uri):
```suggestion
            with self.subTest(uri=uri):
```
nit

2023-04-06 11:59 UTC, robsdedude commented on tests/stub/notifications_config/test_session_notifications_config.py
> +                                          "127.0.0.1") + ":" + str(self._port)
That's exactly `self._server.address`. No need to duplicate the logic.

2023-04-06 11:59 UTC, robsdedude commented on tests/stub/notifications_config/test_session_notifications_config.py
> +                    driver.close()
was this supposed to be in the `finally` block?

2023-04-06 14:59 UTC, robsdedude approved these changes
:film_projector: LGTM except for another small comment

2023-04-06 14:59 UTC, robsdedude commented on tests/stub/notifications_config/test_session_notifications_config.py
> +                    if driver is not None:
Note that when the script doesn't make it to line 76
```python
driver = Driver(self._backend, uri, self._auth)
```
`driver` will not be `None` but undefined => Exception. You'd have to define `driver = None` before the try to be 100% this works as intended.

2023-04-06 15:00 UTC, robsdedude commented on tests/stub/notifications_config/test_session_notifications_config.py
> +                    cursor = session.run("RETURN 1 as n")
```suggestion
                    cursor = session.run("RETURN 1 AS n")
```
nit (`AS` is a keyword) + adjust the script if accepted

2023-10-10 14:49 UTC, closed without merging

2023-10-10 14:49 UTC, thelonelyvulpes commented
Stale