Map server version 5.13 and to protocol version 5.4
neo4j-drivers/testkit pull request #597
Opened 2023-10-04 16:07 UTC by bigmontz

2023-10-04 16:23 UTC, thelonelyvulpes approved these changes

2023-10-04 16:24 UTC, thelonelyvulpes requested changes
I think it need to include a suite too? similar as when 5.9 launched: https://github.com/neo4j-drivers/testkit/pull/572
https://github.com/neo4j-drivers/testkit/pull/571

2023-10-04 16:37 UTC, thelonelyvulpes approved these changes

2023-10-05 07:36 UTC, robsdedude approved these changes
:doughnut:

2023-10-05 09:42 UTC, merged